import "../styles/global.scss";
import ReactQueryProvider from "./ReactQueryProvider";
import RecoilRootWrapper from "./RecoilRootWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
      </head>
      <body>
        <RecoilRootWrapper>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
