import "./global.scss";
import ReactQueryProvider from "./ReactQueryProvider";
import RecoilRootWrapper from "./RecoilRootWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRootWrapper>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
